rule core_clusters:
    input:
        matrix=rules.split_matrices.output.maxlfq,
        eggnog=res("eggnog"),
        gff=res("gff"),
        kegg=res("kegg_names"),
        kegg_classes=res("kegg_classes"),
        code=deps("core_clusters.py"),
    output:
        clusters="results/Clustermap/core_clusters.tsv",
        cog="results/Clustermap/core_cog_enrichment.tsv",
        pathway="results/Clustermap/core_pathway_enrichment.tsv",
    log:
        "logs/core_clusters.log",
    conda:
        "../envs/figures.yaml"
    params:
        outdir=subpath(output.clusters, parent=True),
        day=config["de"]["day"],
        expect=N_DE_RUNS,
        k=config["clusters"]["k"],
        fdr=config["clusters"]["fdr"],
        exclude=QC_EXCLUDE,
        absent=config["absent_replicon"],
        drop_nb=config["kegg"]["drop_non_bacterial"],
        drop_ov=config["kegg"]["drop_overview"],
        drop_ret=config["kegg"]["drop_retired"],
        min_term=config["kegg"]["min_term_size"],
        min_hits=config["kegg"]["min_hits"],
    script:
        "../scripts/core_clusters.py"
