configfile: "config/config.yaml"


container: "docker://condaforge/miniforge3:25.11.0-0"


include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/trimming.smk"
include: "rules/sortmerna.smk"
include: "rules/mapping.smk"
include: "rules/deseq2.smk"
include: "rules/impulseDE2.smk"
include: "rules/mfuzz.smk"
include: "rules/topGO.smk"
include: "rules/figures.smk"
include: "rules/qc.smk"


rule all:
    input:
        get_final_output,
